# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c7344d6954000697ed0164e7dd134ddbe26e1344048105a6b15e0902341df0a4cfd0b8dc9ad62ab68b3911fa004120e2371e434ceef44f9b3d15b7dd480e4dd

test:
  secret_key_base: 9fcf5502546e72f42efa091577234d1086af86a7bf4f9837eaea1be2bbb146dc2b0e44897fc9345810e14436c73191374877a05df6b4aca8a853d72c181f8f08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
